apiVersion: runfabric/v1
kind: provider
id: digitalocean-functions
name: digitalocean-functions
description: External provider plugin for DigitalOcean Functions
version: 0.1.0
pluginVersion: 1
executable: ./bin/digitalocean-plugin
capabilities: [doctor, plan, deploy, remove, invoke, logs]
supportsRuntime: [nodejs, python]
supportsTriggers: [http]
supportsResources: []
permissions:
  fs: true
  env: true
  network: true
  cloud: true
