import type { ProviderCapabilities } from "@runfabric/core";

export const capabilityMatrix: Record<string, ProviderCapabilities> = {
  "aws-lambda": {
    http: true,
    cron: true,
    queue: true,
    storageEvent: true,
    eventbridge: true,
    pubsub: false,
    kafka: false,
    rabbitmq: false,
    streamingResponse: true,
    edgeRuntime: false,
    containerImage: true,
    customRuntime: true,
    backgroundJobs: true,
    websockets: true,
    supportedRuntimes: [
      "nodejs",
      "python",
      "go",
      "java",
      "rust",
      "dotnet"
    ],
    engineRuntime: "custom-runtime",
    maxTimeoutSeconds: 900,
    maxMemoryMB: 10240
  },
  "gcp-functions": {
    http: true,
    cron: true,
    queue: true,
    storageEvent: true,
    eventbridge: false,
    pubsub: true,
    kafka: false,
    rabbitmq: false,
    streamingResponse: false,
    edgeRuntime: false,
    containerImage: true,
    customRuntime: true,
    backgroundJobs: true,
    websockets: false,
    supportedRuntimes: [
      "nodejs",
      "python",
      "go",
      "java",
      "dotnet"
    ],
    engineRuntime: "custom-runtime",
    maxTimeoutSeconds: 3600,
    maxMemoryMB: 32768
  },
  "azure-functions": {
    http: true,
    cron: true,
    queue: true,
    storageEvent: true,
    eventbridge: false,
    pubsub: false,
    kafka: false,
    rabbitmq: false,
    streamingResponse: false,
    edgeRuntime: false,
    containerImage: false,
    customRuntime: false,
    backgroundJobs: true,
    websockets: false,
    supportedRuntimes: [
      "nodejs",
      "python",
      "java",
      "dotnet"
    ],
    engineRuntime: "unsupported",
    maxTimeoutSeconds: 600,
    maxMemoryMB: 4096
  },
  kubernetes: {
    http: true,
    cron: true,
    queue: false,
    storageEvent: false,
    eventbridge: false,
    pubsub: false,
    kafka: false,
    rabbitmq: false,
    streamingResponse: true,
    edgeRuntime: false,
    containerImage: true,
    customRuntime: true,
    backgroundJobs: true,
    websockets: true,
    supportedRuntimes: [
      "nodejs",
      "python",
      "go",
      "java",
      "rust",
      "dotnet"
    ],
    engineRuntime: "container"
  },
  "cloudflare-workers": {
    http: true,
    cron: true,
    queue: false,
    storageEvent: false,
    eventbridge: false,
    pubsub: false,
    kafka: false,
    rabbitmq: false,
    streamingResponse: true,
    edgeRuntime: true,
    containerImage: false,
    customRuntime: false,
    backgroundJobs: false,
    websockets: false,
    supportedRuntimes: [
      "nodejs"
    ],
    engineRuntime: "unsupported"
  },
  vercel: {
    http: true,
    cron: true,
    queue: false,
    storageEvent: false,
    eventbridge: false,
    pubsub: false,
    kafka: false,
    rabbitmq: false,
    streamingResponse: true,
    edgeRuntime: true,
    containerImage: false,
    customRuntime: false,
    backgroundJobs: false,
    websockets: false,
    supportedRuntimes: [
      "nodejs"
    ],
    engineRuntime: "unsupported"
  },
  netlify: {
    http: true,
    cron: true,
    queue: false,
    storageEvent: false,
    eventbridge: false,
    pubsub: false,
    kafka: false,
    rabbitmq: false,
    streamingResponse: false,
    edgeRuntime: false,
    containerImage: false,
    customRuntime: false,
    backgroundJobs: false,
    websockets: false,
    supportedRuntimes: [
      "nodejs"
    ],
    engineRuntime: "unsupported"
  },
  "alibaba-fc": {
    http: true,
    cron: true,
    queue: true,
    storageEvent: true,
    eventbridge: false,
    pubsub: false,
    kafka: false,
    rabbitmq: false,
    streamingResponse: false,
    edgeRuntime: false,
    containerImage: true,
    customRuntime: true,
    backgroundJobs: true,
    websockets: false,
    supportedRuntimes: [
      "nodejs",
      "python",
      "go",
      "java",
      "rust",
      "dotnet"
    ],
    engineRuntime: "custom-runtime",
    maxTimeoutSeconds: 3600,
    maxMemoryMB: 32768
  },
  "digitalocean-functions": {
    http: true,
    cron: true,
    queue: false,
    storageEvent: false,
    eventbridge: false,
    pubsub: false,
    kafka: false,
    rabbitmq: false,
    streamingResponse: false,
    edgeRuntime: false,
    containerImage: false,
    customRuntime: false,
    backgroundJobs: false,
    websockets: false,
    supportedRuntimes: [
      "nodejs"
    ],
    engineRuntime: "unsupported",
    maxTimeoutSeconds: 900,
    maxMemoryMB: 3072
  },
  "fly-machines": {
    http: true,
    cron: false,
    queue: false,
    storageEvent: false,
    eventbridge: false,
    pubsub: false,
    kafka: false,
    rabbitmq: false,
    streamingResponse: true,
    edgeRuntime: false,
    containerImage: true,
    customRuntime: true,
    backgroundJobs: true,
    websockets: true,
    supportedRuntimes: [
      "nodejs",
      "python",
      "go",
      "java",
      "rust",
      "dotnet"
    ],
    engineRuntime: "container",
    maxTimeoutSeconds: 3600,
    maxMemoryMB: 8192
  },
  "ibm-openwhisk": {
    http: true,
    cron: true,
    queue: false,
    storageEvent: false,
    eventbridge: false,
    pubsub: false,
    kafka: false,
    rabbitmq: false,
    streamingResponse: false,
    edgeRuntime: false,
    containerImage: false,
    customRuntime: true,
    backgroundJobs: false,
    websockets: false,
    supportedRuntimes: [
      "nodejs",
      "python",
      "go",
      "java",
      "rust",
      "dotnet"
    ],
    engineRuntime: "custom-runtime",
    maxTimeoutSeconds: 600,
    maxMemoryMB: 512
  }
};
