[request_definition]
r = sub, obj, act, tenant

[policy_definition]
p = role, obj, act, effect

[role_definition]
g = sub, role, tenant

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.role, r.tenant) && r.obj == p.obj && r.act == p.act
