apiVersion: runfabric/v1
kind: provider
id: azure-functions
name: azure-functions
description: External provider plugin for Azure Functions
version: 0.1.0
pluginVersion: 1
executable: ./bin/azure-plugin
capabilities: [doctor, plan, deploy, remove, invoke, logs]
supportsRuntime: [nodejs, python]
supportsTriggers: [http]
supportsResources: []
permissions:
  fs: true
  env: true
  network: true
  cloud: true
